

select * from ACMATT 
select * from ACMBANK 
select * from ACMBANKLIST 
select * from ACMBANKNUM 
select * from ACMBANKS 
select * from ACMBTOB 
select * from ACMBUDGET ORDER BY NAME 

select CorpSno	,Code	,Kind	,Chkno	,Chkdate	,Money,	Bank,	Account,	Note,	Prdt
 from ACMCASH

--select CorpSno	,Code	,Kind	,Chkno	,Chkdate	,Money,	Bank,	Account,	Note,	Prdt 
--from ACMCASHPH
select * from ACMCASHPH
select * from ACMCASHPRED
select * from ACMCHKB 
select * from ACMCOMMAPP
select * from ACMCUST
select * from ACMDEBIT 
select * from acmdepta 
select * from acmdeptp
select * from ACMDEPTR
select * from ACMDEPTS
select * from ACMHEAD 
select * from acmhead_p 
select * from acmhead_pr 
select * from acmhead2 
select * from acmhouse 
select * from ACMBANK
select * from ACMATT
select * from ACMBANKLIST
select * from ACMBANKNUM
select * from ACMBANKS
select * from ACMBTOB
select * from ACMBUDGET
select * from ACMCASH
select * from ACMCASHPH
select * from ACMCASHPRED
select * from ACMCHKB
select * from ACMCOMMAPP
select * from ACMCUST
select * from ACMDEBIT
select * from ACMDEPTA
select * from ACMDEPTP
select * from ACMDEPTR
select * from ACMDEPTRP
select * from ACMDEPTS
select * from ACMHEAD
select * from ACMHEAD_P
select * from ACMHEAD_PR
select * from acmhead2
select * from ACMHOUSE
select * from ACMICHK
select * from ACMINIF
select * from ACMINV
select * from ACMINVLIST
select * from ACMINVNO
select * from ACMINVNUM
select * from ACMINVS
select * from ACMINVS2
select * from ACMINVS3
select * from ACMJOUR_P
select * from ACMJOUR1
select * from ACMJOUR2
select * from ACMJOURD
select * from ACMJOURDS
select * from ACMJOURS
select * from ACMJOURSH
select * from ACMLNOTE
select * from ACMLSALE
select * from ACMMAPP
select * from ACMOTHR
select * from ACMPAYD
select * from ACMPAYDP
select * from ACMPAYH
select * from ACMPAYI
select * from ACMPAYM
select * from ACMPAYT
select * from ACMPRDTC
select * from ACMPRDTC_2
select * from ACMPREDD
select * from ACMPREDH
select * from ACMPREDS
select * from ACMQCONT
select * from ACMQCONTB
select * from ACMREFD
select * from ACMREFH
select * from ACMREFXD
select * from ACMREFXH
select * from ACMSALED
select * from ACMSALEH
select * from ACMSALEM
select * from ACMSIGN
select * from ACMSTDI
select * from ACMTOTBBD
select * from ACMTOTBHR
select * from ACMTOTSTD
select * from ACMUCHK
select * from AfmAcmM
