select * from ITEMPRDT
select * from GWCONTDETL order by  Tdate


select * from GWBUDGET
select * from GHHEAD
select * from GWCONPAYT
select * from GWCONTDETL
select * from ACMTOTBBD
select * from GWCONTHSH
select * from GWCONTRACT
select * from ACMTOTBHR
select * from GWCPAY
select * from PRDTGRAD
select * from GHITEM
select * from PRDTSPEC
select * from RECO
select * from AWMORDERH
select * from GHJOUR
select * from AHMOTHRMAPR
select * from AWMCONTRACTa
select * from AHMOTHRPAYD
select * from ACMATT
select * from AHMOTHRPAYT
select * from GWCONTDDSH
select * from AHMOTHRPRDT
select * from CORP
select * from DIGEST
select * from ACMBANK
select * from ACMBUDGET
select * from ACMREFXH
select * from JOUR
select * from OTHR
select * from ACMCUST
select * from PRDT
select * from PRDTATT
select * from ITEMATT
select * from ACMDEPT
select * from AWMBUDALT_old
select * from AWMBUDALT
select * from AHMR_REFH
select * from JOUR1
select * from ACMPAYH
select * from AHMCHEQ
select * from JOUR2
select * from AWMCONTRACTZ
select * from AHMR_SALEH
select * from ACMPRDTC_2
select * from ACMHEAD_P
select * from ACMPRDTC
select * from ACMBANKS
select * from AHMATT
select * from HEAD
select * from AHMR_REVH
select * from ACMHEAD
select * from AWMBUDALTD
select * from AWMBUDALTH
select * from AWMBUDGET
select * from ACMJOUR
select * from AHMCONTATT
select * from AHMSLCASH
select * from AWMBYP
select * from ACMJOUR_P
select * from AHMH_HITEM
select * from AWMCONTATT
select * from ACMJOUR1
select * from itemupa2
select * from AWMCHEQ
select * from AWMCONALTD
select * from AWMCONALTH
select * from ACMJOUR2
select * from AWMCONPAYD
select * from AWMCONPAYO
select * from AWMCONPAYT
select * from AWMCONQDETL
select * from ITEMUPA
select * from AWMCONQRY
select * from AWMCONTDETL
select * from AWMCONTDS
select * from AWMCONTHS
select * from AWMBUDGET_BAK
select * from ACMLNOTE
select * from ALLPRDT
select * from AWMCONTRACT
select * from AWMCONTRACT
select * from GHINVN
select * from AWMH_CON1
select * from AWMH_CON2
select * from ACMMAPP
select * from AHMHITEM
select * from AWMINPDATE
select * from ACMOTHR
select * from AWMINPDETL
select * from AWMINPDTLH
select * from AWMINPHOTO
select * from AWMINVOICE
select * from AWMOTHRMAPR
select * from AWMOTHRPAYD
select * from GHCOMMUH
select * from AWMOTHRPAYT
select * from AWMOTHRPRDT
select * from AHMINV
select * from ACMQCONT
select * from ACMREFH
select * from CURRNAME
select * from CURRRATE
select * from AWMATT
select * from ITEM
select * from ACMSALEH