

--[dbo].[AWMCONTDETL].[Name]

select * from ACMATT

--[dbo].[ACMJOUR].[Dept]

select distinct rcode from ACMJOUR  order by rcode  

select * from AHMGARAGE
select distinct code  from BANKNAME    

select * from ACMHOUSE
select * from ACMINVS
select * from AHMSLCASH
select * from AWMCALC1
select * from AWMCHEQ
select * from ACMJOURSH

select distinct flg from ACMJOURSH
select * from ACMJOURSH
select * from ALLPRDT
select * from AWMINPDATE
select * from AWMINPDATE
select * from AWMINPDETL
select * from AWMINPDETL
select * from AWMINPDTLH
select * from AWMINVOICE
select * from AHMINV

select distinct flg from AHMINV
select * from AWMSIGN
select * from ACMATT


--Mcode

-------------------
SELECT * FROM AHMLCONT
SELECT * FROM AHMLDELAY
SELECT * FROM AHMLITEM
SELECT * FROM AHMLNOTE
SELECT * FROM AHMLPASS
SELECT * FROM AWMORDERH
SELECT * FROM AHMOTHRMAPR
SELECT * FROM AHMOTHRPAYD
SELECT * FROM ACMATT
SELECT * FROM AHMOTHRPAYT
SELECT * FROM PRDTATT
SELECT * FROM ITEMATT
SELECT * FROM AHMR_LSALE
SELECT * FROM AHMBYPASS
SELECT * FROM AWMBUDALT
SELECT * FROM AHMCASH
SELECT * FROM ACMPAYH
SELECT * FROM AWMCONTDLX
SELECT * FROM AHMCHEQ
SELECT * FROM AHMDAYM2
SELECT * FROM AHMATT
SELECT * FROM AHMH_CASH
SELECT * FROM AHMDAYM
SELECT * FROM AWMBYP
SELECT * FROM AWMCONTATT
SELECT * FROM AWMCHEQ
SELECT * FROM AHMH_LCONT
SELECT * FROM AWMCONPAYD
SELECT * FROM AHMH_LDELAY
SELECT * FROM AWMCONPAYO
SELECT * FROM AWMCONPAYT
SELECT * FROM AHMH_LITEM
SELECT * FROM AHMALLOWANCE1
SELECT * FROM AHMH_LNOTE
SELECT * FROM AHMH_LPASS
SELECT * FROM AHMINVLIST1
SELECT * FROM AWMCONTPDD
SELECT * FROM AWMCONTRACT
SELECT * FROM GHPREDRES
SELECT * FROM AWMINPDTLH
SELECT * FROM AWMINPHOTO
SELECT * FROM AWMINVOICE
SELECT * FROM AWMOTHRMAPR
SELECT * FROM AWMOTHRPAYD
SELECT * FROM AWMOTHRPAYT
SELECT * FROM AHMINV
SELECT * FROM ACMREFH
SELECT * FROM AWMBYPASS
SELECT * FROM AHMINVOICE
SELECT * FROM AWMATT
SELECT * FROM ACMSALEH
